volumes:
  postgres-data-dev:
    driver: local
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGODB_URI: ${MONGODB_URI}

  postgres:
    image: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}

  reservation:
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development 
    command: pnpm start:dev reservation
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on: [postgres, mongo]
    environment:
      MONGODB_URI: ${MONGODB_URI}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm start:dev auth
    ports:
      - '3001:3001'
    environment:
      MONGODB_URI: ${MONGODB_URI}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on: [postgres, mongo]
