volumes:
  postgres-data-dev:
    driver: local
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - ./libs/common/.env

  postgres:
    image: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    env_file:
      - ./libs/common/.env

  reservation:
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development 
    # command: pnpm start:dev reservation
    command: 
      - /bin/sh
      - -c
      - | 
        pnpm run typeorm -d ./apps/reservation/src/db/data-source.ts migration:run
        pnpm start:dev reservation
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on: [postgres, mongo]
    env_file:
      - ./libs/common/.env
      - ./apps/reservation/.env
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    # command: pnpm start:dev auth
    command: 
      - /bin/sh
      - -c
      - |
        pnpm run typeorm -d ./apps/auth/src/db/data-source.ts migration:run  
        pnpm start:dev auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    env_file:
      - ./libs/common/.env
      - ./apps/auth/.env
    depends_on: [postgres, mongo]
